### PR TITLE
Ammondation color

### LINKED ISSUE #55: Matching colors
Would it be an idea, to use the same color that we use for the 'menu' box on the left for the 'admonition' box ?

match-colors

Currently the 'admonition' box is a bit darker

### PR DESCRIPTION
**Pull request by loechel**
this fixes #55

### CODE REVIEW

**Comment by loechel** [comment]
@svx please approve and merge

**Comment by svx** [comment]
@loechel want me to merge or should I wait ?

**Comment by loechel** [comment]
@svx merge please. This branch is actually a base for an already merged pull. This does the changes to the old designs.

**Comment by svx** [comment]
done !

**Pull request merged**
