### PR TITLE
Update doormat.html

### PR DESCRIPTION
**Pull request by tkimnguyen**
changed names of links and updated some old links... but I think this must not be exactly what appears on docs.plone.org

### CODE REVIEW

**Comment by tkimnguyen** [comment]
@svx is there documentation on where the actual doormat is overridden for docs.plone.org?

**Comment by svx** [comment]
I would like to suggest that we use the same terms as we do on docs.plone.org,  training.plone.org and so on.

These would be for example:

*Forum* in place of `Community discussion`  otherwise it is just confusing .... :)

**Comment by svx** [comment]
@tkimnguyen docs are of course under /docs:

https://github.com/plone/sphinx.themes.plone/blob/master/docs/index.rst

under *advanced* you can find the part about the doormat .....

**Comment by svx** [comment]
@tkimnguyen, please update the Changelog, thanks !

**Comment by tkimnguyen** [comment]
Updated to use consistent terms from footer of Plone.org

**Comment by tkimnguyen** [comment]
Looking at Advanced Usage you refer to, sorry, I still don't understand why the doormat in this repo does not match what I see live on docs.plone.org, but it's not important. If it becomes a problem I'll yell :)

**Comment by svx** [comment]
Because this is a template and this of course gets overwritten by the changes in the docs itself, see https://github.com/plone/documentation/blob/5.1/_templates/doormat.html

Sorry, I thought this is logical, maybe we need to adjust the docs .....

**Comment by tkimnguyen** [comment]
if this looks ok as is please merge and close

**Comment by jensens** [comment]
@tkimnguyen may you change this at plone/documentation repos as well?

**Pull request merged**
