### PR TITLE
Add gitter chat button

### PR DESCRIPTION
**Pull request by loechel**

### CODE REVIEW

**Comment by loechel** [comment]
this solves #47 

@svx please look if it now fits your wishes. If so merge and deploy.

Or If I should also fix @tkimnguyen wish to rename "Feedback" to "Report a bug"?

**Comment by loechel** [comment]
I renamed it.

**Comment by tkimnguyen** [comment]
Thx @loechel and @svx !

**Comment by svx** [comment]
@tkimnguyen 

Thanks, but you were a bit too fast, with merging, there was a reason why I did not merged, yet. :)

These changes has to be included into https://github.com/plone/sphinx.themes.plone/tree/ploneorg5_adjustmens.

**Comment by loechel** [comment]
@svx I will rebase the ploneorg5_adjustments and resolve the errors

**Comment by tkimnguyen** [comment]
Ah sorry @svx - I will refrain from merging PRs in this repo...

**Pull request merged**
