### PR TITLE
Fix Accessibility issues with title element.

### PR DESCRIPTION
**Pull request by loechel**
Fix issue #51

### CODE REVIEW

**Comment by svx** [comment]
Ok one moment before we do something, what will mess up something else .... :)

@loechel are you saying this is/was already in https://github.com/plone/sphinx.themes.plone/tree/ploneorg5_adjustmens ?

**If so** we do not need to merge this PR here.
**If not** we need to rebase the ploneorg5-adjustmens branch, after this merge here.

Sorry I am getting confused :)

**Comment by svx** [comment]
Ok, looks like it is not yet in: https://github.com/plone/sphinx.themes.plone/blob/ploneorg5_adjustmens/src/sphinx/themes/plone/plone_basic/topbar.html.

Who wants to merge and rebase the other branch ?

I can merge here, but I suck with rebeasing :)

**Comment by svx** [comment]
@loechel the reason why it is not on docs.plone.org is yet, because it is meant for 5.1 :)

**Comment by svx** [comment]
Since I don't think we will make a release before 5.1 maybe we should merge the other branch, because it is getting annoying to rebase the other branch all the time.

Or people should commit till release only to the other branch

**Comment by loechel** [comment]
@svx The fixes in the topbar with the old theme is already merged, but I did see that the title accessibility was something else than that so fixed that. 

So please merge, I will rebase the other branch. And you could use the currently fixed theme, it still looks the same as before, but with fixed topbar.

**Comment by svx** [comment]
@loechel done !

**Comment by loechel** [comment]
just for info, the rebase also has happend.

**Comment by svx** [comment]
Thanks a lot !

**Pull request merged**
